---
#############################################################
# Particle breakup process settings                         #
#############################################################

background_metric: "Kerr-Schild Kerr"
background_radius: 1000000.0

KerrSchild_Kerr_Settings:
  M: 0.5
  a: 0.49

energy_threshold: 1.0

output_format: ".ascii"

# Zero for photons, anything else for massive.
particle_type: 1

breakup_point:
  X1: 1.0
  X2: 0.0
  X3: 0.0

# Param: -25/100 * pi
# Particle Mass 1.0e-1
trajectory_1:
  final_time: -10000000.0
  output_times: 1000
  
  initial_V1: 0.6769503786998466
  initial_V2: 0.6740022058848380
  initial_V3: 0.0
  
  initial_EN: 1.0

# Elipse param: -100/200 * pi
# Particle mass: 1.0e-4
trajectory_2:
  final_time: 10000000.0
  output_times: 1000

  initial_V1: 0.5948571400034293
  initial_V2: -0.3343724878526367
  initial_V3: 0.0

  initial_EN: 8.0e-3

trajectory_3:
  final_time: 10000000.0
  output_times: 1000
