#include "KerrSchild_Kerr.hpp"
#include "aux_functions.hpp"

using grlensing::KerrSchild_Kerr;
using grlensing::metric_server;
using ksk_aux::d_r_KS_dx;
using ksk_aux::d_r_KS_dy;
using ksk_aux::d_r_KS_dz;
using ksk_aux::Power;
using ksk_aux::r_KS;
using ksk_aux::Sqrt;

GRLENSING_KERRSCHILD_KERR_METRIC_API auto KerrSchild_Kerr::ll_extrinsic(double, double x, double y,
                                                                        double z)
    -> metric_server::spatial_matrix {

  auto r = [&](double x, double y, double z) { return r_KS(a, x, y, z); };
  auto dr_dx = [&](double x, double y, double z) { return d_r_KS_dx(a, x, y, z); };
  auto dr_dy = [&](double x, double y, double z) { return d_r_KS_dy(a, x, y, z); };
  auto dr_dz = [&](double x, double y, double z) { return d_r_KS_dz(a, x, y, z); };

  metric_server::spatial_matrix K;
  K[0][0]
      = (2 * M * Power(r(x, y, z), 2)
         * (Power(r(x, y, z), 16) + 3 * Power(a, 11) * y * Power(z, 4) * dr_dx(x, y, z)
            + 2 * Power(a, 9) * (2 * a * x + M * y) * Power(z, 4) * r(x, y, z) * dr_dx(x, y, z)
            - 4 * Power(a, 2) * x * Power(r(x, y, z), 13) * dr_dx(x, y, z)
            - 2 * x * Power(r(x, y, z), 15) * dr_dx(x, y, z)
            + 3 * a * Power(r(x, y, z), 14) * (a - y * dr_dx(x, y, z))
            + Power(a, 6) * Power(z, 2) * Power(r(x, y, z), 4)
                  * (a * (-8 * M * x * y + 3 * a * Power(z, 2))
                     + M * (5 * Power(x, 2) + 2 * Power(y, 2)) * z * dr_dz(x, y, z)
                     + M * y * (-8 * Power(x, 2) + 3 * Power(y, 2)) * dr_dy(x, y, z)
                     + (y * (2 * Power(a, 3) + 11 * M * x * y)
                        + (6 * M * x + 5 * a * y) * Power(z, 2))
                           * dr_dx(x, y, z))
            + Power(a, 7) * Power(z, 2) * Power(r(x, y, z), 3)
                  * (M * y * (-2 * a * y + 8 * x * z * dr_dz(x, y, z) - 3 * x * y * dr_dy(x, y, z))
                     + (3 * M * Power(y, 3) + 2 * (5 * a * x + 3 * M * y) * Power(z, 2))
                           * dr_dx(x, y, z))
            + Power(a, 2) * Power(r(x, y, z), 8)
                  * (Power(a, 2)
                         * (-4 * a * M * x * y + 6 * Power(a, 2) * Power(z, 2) + Power(z, 4))
                     + M * z
                           * (Power(a, 2) * (Power(x, 2) - 6 * Power(y, 2))
                              + Power(x, 2) * Power(z, 2))
                           * dr_dz(x, y, z)
                     + M * y * (-(Power(a, 2) * Power(y, 2)) + Power(x, 2) * Power(z, 2))
                           * dr_dy(x, y, z)
                     + (-(Power(a, 2) * y * (Power(a, 3) + M * x * y))
                        + (6 * Power(a, 2) * M * x + 3 * M * Power(x, 3) - 2 * Power(a, 3) * y
                           + 2 * M * x * Power(y, 2))
                              * Power(z, 2)
                        + 2 * M * x * Power(z, 4))
                           * dr_dx(x, y, z))
            + Power(a, 3) * Power(r(x, y, z), 7)
                  * (2 * a * M * (-4 * Power(x, 2) + Power(y, 2)) * Power(z, 2)
                     + M * x * (a * y - x * z) * (a * y + x * z) * dr_dy(x, y, z)
                     + (-(Power(a, 2) * M * Power(y, 3))
                        + (8 * Power(a, 3) * x + 3 * M * (2 * Power(a, 2) + Power(x, 2)) * y
                           + 2 * M * Power(y, 3))
                              * Power(z, 2)
                        + 2 * (a * x + M * y) * Power(z, 4))
                           * dr_dx(x, y, z))
            + Power(r(x, y, z), 12)
                  * (a * (3 * Power(a, 3) + 4 * M * x * y + 2 * a * Power(z, 2))
                     - 3 * M * Power(x, 2) * (z * dr_dz(x, y, z) + y * dr_dy(x, y, z))
                     + (-(M * Power(x, 3)) - 7 * Power(a, 3) * y
                        + 2 * M * x * (Power(y, 2) + Power(z, 2)))
                           * dr_dx(x, y, z))
            + Power(a, 2) * Power(r(x, y, z), 9)
                  * (-2 * M
                         * (2 * Power(a, 2) * (x - y) * (x + y) + Power(x, 2) * Power(z, 2)
                            + 4 * a * x * y * z * dr_dz(x, y, z))
                     - a * M * x * (Power(x, 2) - 5 * Power(y, 2)) * dr_dy(x, y, z)
                     + a
                           * (4 * a * x * Power(z, 2)
                              + 3 * M * y * (Power(x, 2) - Power(y, 2) + 2 * Power(z, 2)))
                           * dr_dx(x, y, z))
            + Power(a, 2) * Power(r(x, y, z), 10)
                  * (Power(a, 4) + 6 * Power(a, 2) * Power(z, 2)
                     - M * (2 * Power(x, 2) + 5 * Power(y, 2)) * z * dr_dz(x, y, z)
                     + M * y * (9 * Power(x, 2) - 5 * Power(y, 2)) * dr_dy(x, y, z)
                     + (-5 * Power(a, 3) * y - 2 * a * y * Power(z, 2)
                        + M * x * (3 * Power(x, 2) - 11 * Power(y, 2) + 6 * Power(z, 2)))
                           * dr_dx(x, y, z))
            + Power(a, 5) * Power(z, 2) * Power(r(x, y, z), 5)
                  * (M * x
                         * (-6 * a * x + 8 * y * z * dr_dz(x, y, z)
                            + (-5 * Power(x, 2) + 9 * Power(y, 2)) * dr_dy(x, y, z))
                     + (4 * Power(a, 3) * x + 2 * Power(a, 2) * M * y + 8 * a * x * Power(z, 2)
                        + M * y * (15 * Power(x, 2) + Power(y, 2) + 6 * Power(z, 2)))
                           * dr_dx(x, y, z))
            + a * Power(r(x, y, z), 11)
                  * (M
                         * (-4 * a * (x - y) * (x + y) - 8 * x * y * z * dr_dz(x, y, z)
                            + x * (3 * Power(x, 2) - 8 * Power(y, 2)) * dr_dy(x, y, z))
                     + (-2 * Power(a, 3) * x
                        + M * y * (-9 * Power(x, 2) + 2 * (Power(y, 2) + Power(z, 2))))
                           * dr_dx(x, y, z))
            + Power(a, 8) * Power(z, 3) * Power(r(x, y, z), 2)
                  * (3 * M * Power(y, 2) * dr_dz(x, y, z)
                     + z * (Power(a, 2) + (2 * M * x + 7 * a * y) * dr_dx(x, y, z)))
            + Power(a, 4) * z * Power(r(x, y, z), 6)
                  * (-(M
                       * (-6 * Power(x, 2) * Power(z, 2)
                          + Power(y, 2) * (Power(a, 2) + Power(z, 2)))
                       * dr_dz(x, y, z))
                     + z
                           * (a * (2 * Power(a, 3) - 8 * M * x * y + 3 * a * Power(z, 2))
                              - M * y * (-5 * Power(x, 2) + Power(y, 2)) * dr_dy(x, y, z)
                              + (2 * Power(a, 2) * M * x + 2 * Power(a, 3) * y + a * y * Power(z, 2)
                                 + M * x * (7 * Power(x, 2) + Power(y, 2) + 6 * Power(z, 2)))
                                    * dr_dx(x, y, z)))))
        / (Power(Power(a, 2) + Power(r(x, y, z), 2), 3)
           * Power(Power(a, 2) * Power(z, 2) + Power(r(x, y, z), 4), 2)
           * (Power(a, 4) * Power(z, 2) + 2 * Power(a, 2) * M * Power(z, 2) * r(x, y, z)
              + Power(a, 2) * Power(z, 2) * Power(r(x, y, z), 2)
              + 2 * M * (Power(x, 2) + Power(y, 2) + Power(z, 2)) * Power(r(x, y, z), 3)
              + Power(a, 2) * Power(r(x, y, z), 4) + Power(r(x, y, z), 6))
           * Sqrt(
               1
               - (2 * M * Power(r(x, y, z), 3) * (Power(a, 2) + Power(r(x, y, z), 2)))
                     / (Power(a, 4) * Power(z, 2) + 2 * Power(a, 2) * M * Power(z, 2) * r(x, y, z)
                        + Power(a, 2) * Power(z, 2) * Power(r(x, y, z), 2)
                        + 2 * M * (Power(x, 2) + Power(y, 2) + Power(z, 2)) * Power(r(x, y, z), 3)
                        + Power(a, 2) * Power(r(x, y, z), 4) + Power(r(x, y, z), 6))));
  K[0][1]
      = (M * Power(r(x, y, z), 2)
         * (3 * Power(a, 11) * Power(z, 4) * (y * dr_dy(x, y, z) - x * dr_dx(x, y, z))
            + 3 * a * Power(r(x, y, z), 14) * (-(y * dr_dy(x, y, z)) + x * dr_dx(x, y, z))
            - 4 * Power(a, 2) * Power(r(x, y, z), 13) * (x * dr_dy(x, y, z) + y * dr_dx(x, y, z))
            - 2 * Power(r(x, y, z), 15) * (x * dr_dy(x, y, z) + y * dr_dx(x, y, z))
            + 2 * Power(a, 9) * Power(z, 4) * r(x, y, z)
                  * ((2 * a * x + M * y) * dr_dy(x, y, z) + (-(M * x) + 2 * a * y) * dr_dx(x, y, z))
            + Power(a, 8) * Power(z, 3) * Power(r(x, y, z), 2)
                  * (-6 * M * x * y * dr_dz(x, y, z) + (2 * M * x + 7 * a * y) * z * dr_dy(x, y, z)
                     + (-7 * a * x + 2 * M * y) * z * dr_dx(x, y, z))
            + Power(a, 2) * Power(r(x, y, z), 10)
                  * (6 * M * x * y * z * dr_dz(x, y, z)
                     + (-6 * M * Power(x, 3) - 5 * Power(a, 3) * y + 22 * M * x * Power(y, 2)
                        + 6 * M * x * Power(z, 2) - 2 * a * y * Power(z, 2))
                           * dr_dy(x, y, z)
                     + (5 * Power(a, 3) * x + 22 * M * Power(x, 2) * y - 6 * M * Power(y, 3)
                        + 2 * (a * x + 3 * M * y) * Power(z, 2))
                           * dr_dx(x, y, z))
            + 2 * Power(a, 5) * Power(z, 2) * Power(r(x, y, z), 5)
                  * (-6 * a * M * x * y + 4 * M * (-Power(x, 2) + Power(y, 2)) * z * dr_dz(x, y, z)
                     + (2 * Power(a, 3) * x + Power(a, 2) * M * y + 4 * a * x * Power(z, 2)
                        + M * y * (-9 * Power(x, 2) + 5 * Power(y, 2) + 3 * Power(z, 2)))
                           * dr_dy(x, y, z)
                     + (-(Power(a, 2) * M * x) + 2 * Power(a, 3) * y + 4 * a * y * Power(z, 2)
                        + M * x * (-5 * Power(x, 2) + 9 * Power(y, 2) - 3 * Power(z, 2)))
                           * dr_dx(x, y, z))
            + 2 * Power(a, 3) * Power(r(x, y, z), 7)
                  * (-10 * a * M * x * y * Power(z, 2)
                     + (-(Power(a, 2) * M * Power(x, 2) * y)
                        + (4 * Power(a, 3) * x + 3 * Power(a, 2) * M * y + M * Power(y, 3))
                              * Power(z, 2)
                        + (a * x + M * y) * Power(z, 4))
                           * dr_dy(x, y, z)
                     + (4 * Power(a, 3) * y * Power(z, 2) + a * y * Power(z, 4)
                        + Power(a, 2) * M * x * (Power(y, 2) - 3 * Power(z, 2))
                        - M * x * Power(z, 2) * (Power(x, 2) + Power(z, 2)))
                           * dr_dx(x, y, z))
            + 2 * Power(a, 7) * Power(z, 2) * Power(r(x, y, z), 3)
                  * (2 * a * M * x * y + 4 * M * (-Power(x, 2) + Power(y, 2)) * z * dr_dz(x, y, z)
                     + (5 * a * x * Power(z, 2) + 3 * M * y * (Power(x, 2) + Power(z, 2)))
                           * dr_dy(x, y, z)
                     + (5 * a * y * Power(z, 2) - 3 * M * x * (Power(y, 2) + Power(z, 2)))
                           * dr_dx(x, y, z))
            + Power(r(x, y, z), 12)
                  * (4 * a * M * (-Power(x, 2) + Power(y, 2)) - 6 * M * x * y * z * dr_dz(x, y, z)
                     + (-7 * Power(a, 3) * y
                        + 2 * M * x * (Power(x, 2) - 2 * Power(y, 2) + Power(z, 2)))
                           * dr_dy(x, y, z)
                     + (7 * Power(a, 3) * x
                        + 2 * M * y * (-2 * Power(x, 2) + Power(y, 2) + Power(z, 2)))
                           * dr_dx(x, y, z))
            + 2 * a * Power(r(x, y, z), 11)
                  * (-8 * a * M * x * y + 4 * M * (x - y) * (x + y) * z * dr_dz(x, y, z)
                     + (-(Power(a, 3) * x)
                        + M * y * (8 * Power(x, 2) - 3 * Power(y, 2) + Power(z, 2)))
                           * dr_dy(x, y, z)
                     - (Power(a, 3) * y
                        + M * x * (-3 * Power(x, 2) + 8 * Power(y, 2) + Power(z, 2)))
                           * dr_dx(x, y, z))
            + Power(a, 2) * Power(r(x, y, z), 8)
                  * (4 * Power(a, 3) * M * (x - y) * (x + y)
                     + 2 * M * x * y * z * (7 * Power(a, 2) + Power(z, 2)) * dr_dz(x, y, z)
                     + (-(Power(a, 5) * y) - 2 * Power(a, 3) * y * Power(z, 2)
                        + 2 * M * x * Power(z, 2) * (Power(x, 2) + 2 * Power(y, 2) + Power(z, 2))
                        + 2 * Power(a, 2) * M * x * (Power(y, 2) + 3 * Power(z, 2)))
                           * dr_dy(x, y, z)
                     + (Power(a, 5) * x + 2 * Power(a, 3) * x * Power(z, 2)
                        + 2 * M * y * Power(z, 2) * (2 * Power(x, 2) + Power(y, 2) + Power(z, 2))
                        + 2 * Power(a, 2) * M * y * (Power(x, 2) + 3 * Power(z, 2)))
                           * dr_dx(x, y, z))
            + 2 * Power(a, 2) * Power(r(x, y, z), 9)
                  * (-2 * M * x * y * (4 * Power(a, 2) + Power(z, 2))
                     + 4 * a * M * (x - y) * (x + y) * z * dr_dz(x, y, z)
                     + a
                           * (2 * a * x * Power(z, 2)
                              + M * y * (-5 * Power(x, 2) + Power(y, 2) + 3 * Power(z, 2)))
                           * dr_dy(x, y, z)
                     + a
                           * (2 * a * y * Power(z, 2)
                              - M * x * (Power(x, 2) - 5 * Power(y, 2) + 3 * Power(z, 2)))
                           * dr_dx(x, y, z))
            + Power(a, 6) * Power(z, 2) * Power(r(x, y, z), 4)
                  * (8 * a * M * (x - y) * (x + y) + 6 * M * x * y * z * dr_dz(x, y, z)
                     + (2 * Power(a, 3) * y + 5 * a * y * Power(z, 2)
                        + 2 * M * x * (4 * Power(x, 2) - 7 * Power(y, 2) + 3 * Power(z, 2)))
                           * dr_dy(x, y, z)
                     + (-2 * Power(a, 3) * x - 5 * a * x * Power(z, 2)
                        + 2 * M * y * (-7 * Power(x, 2) + 4 * Power(y, 2) + 3 * Power(z, 2)))
                           * dr_dx(x, y, z))
            + Power(a, 4) * z * Power(r(x, y, z), 6)
                  * (2 * M * x * y * (Power(a, 2) + 7 * Power(z, 2)) * dr_dz(x, y, z)
                     + z
                           * (8 * a * M * (x - y) * (x + y)
                              + (2 * Power(a, 2) * M * x + 2 * Power(a, 3) * y + a * y * Power(z, 2)
                                 + 2 * M * x * (Power(x, 2) + 7 * Power(y, 2) + 3 * Power(z, 2)))
                                    * dr_dy(x, y, z)
                              + (-2 * Power(a, 3) * x + 2 * Power(a, 2) * M * y
                                 - a * x * Power(z, 2)
                                 + 2 * M * y * (7 * Power(x, 2) + Power(y, 2) + 3 * Power(z, 2)))
                                    * dr_dx(x, y, z)))))
        / (Power(Power(a, 2) + Power(r(x, y, z), 2), 3)
           * Power(Power(a, 2) * Power(z, 2) + Power(r(x, y, z), 4), 2)
           * (Power(a, 4) * Power(z, 2) + 2 * Power(a, 2) * M * Power(z, 2) * r(x, y, z)
              + Power(a, 2) * Power(z, 2) * Power(r(x, y, z), 2)
              + 2 * M * (Power(x, 2) + Power(y, 2) + Power(z, 2)) * Power(r(x, y, z), 3)
              + Power(a, 2) * Power(r(x, y, z), 4) + Power(r(x, y, z), 6))
           * Sqrt(
               1
               - (2 * M * Power(r(x, y, z), 3) * (Power(a, 2) + Power(r(x, y, z), 2)))
                     / (Power(a, 4) * Power(z, 2) + 2 * Power(a, 2) * M * Power(z, 2) * r(x, y, z)
                        + Power(a, 2) * Power(z, 2) * Power(r(x, y, z), 2)
                        + 2 * M * (Power(x, 2) + Power(y, 2) + Power(z, 2)) * Power(r(x, y, z), 3)
                        + Power(a, 2) * Power(r(x, y, z), 4) + Power(r(x, y, z), 6))));
  K[0][2]
      = (M * r(x, y, z)
         * (-3 * a * y * Power(r(x, y, z), 13) * dr_dz(x, y, z)
            + 2 * Power(a, 10) * Power(z, 5) * dr_dx(x, y, z)
            - 2 * Power(a, 2) * z * Power(r(x, y, z), 8)
                  * (2 * (Power(a, 2) * M * x + Power(a, 3) * y + M * x * Power(z, 2))
                     - 2 * a * (a * x - 2 * M * y) * z * dr_dz(x, y, z)
                     - a * M * (Power(x, 2) - 2 * Power(y, 2)) * dr_dy(x, y, z)
                     + a * (Power(a, 3) + 3 * M * x * y) * dr_dx(x, y, z))
            - 2 * Power(r(x, y, z), 14) * (x * dr_dz(x, y, z) + z * dr_dx(x, y, z))
            - 2 * Power(a, 2) * Power(r(x, y, z), 12)
                  * (x * dr_dz(x, y, z) + 3 * z * dr_dx(x, y, z))
            + Power(a, 8) * Power(z, 4) * r(x, y, z)
                  * (3 * a * y * dr_dz(x, y, z) + 2 * M * z * dr_dx(x, y, z))
            + 2 * Power(a, 6) * Power(z, 3) * Power(r(x, y, z), 3)
                  * (-(a * (a * x + 2 * M * y)) + 2 * (2 * M * x + a * y) * z * dr_dz(x, y, z)
                     - 2 * M * x * y * dr_dy(x, y, z)
                     + M * (2 * Power(y, 2) + 3 * Power(z, 2)) * dr_dx(x, y, z))
            + 2 * Power(a, 5) * Power(z, 3) * Power(r(x, y, z), 4)
                  * (-2 * a * (2 * M * x + a * y) + (3 * a * x + 4 * M * y) * z * dr_dz(x, y, z)
                     + M * (-3 * Power(x, 2) + 2 * Power(y, 2)) * dr_dy(x, y, z)
                     + (5 * M * x * y + 3 * a * Power(z, 2)) * dr_dx(x, y, z))
            + 2 * Power(a, 2) * z * Power(r(x, y, z), 7)
                  * (-(Power(a, 2) * x * (Power(a, 2) + Power(z, 2)))
                     + M * x * z * (Power(x, 2) + Power(y, 2) + 2 * Power(z, 2)) * dr_dz(x, y, z)
                     + M * x * y * (2 * Power(a, 2) + Power(z, 2)) * dr_dy(x, y, z)
                     + M
                           * (-2 * Power(a, 2) * Power(y, 2)
                              + (3 * Power(a, 2) + 2 * Power(x, 2) + Power(y, 2)) * Power(z, 2)
                              + Power(z, 4))
                           * dr_dx(x, y, z))
            - 2 * a * Power(r(x, y, z), 10)
                  * (-(M * y * (Power(x, 2) + Power(y, 2) - 3 * Power(z, 2)) * dr_dz(x, y, z))
                     + z
                           * (a * (2 * M * x + a * y)
                              + M * (-3 * Power(x, 2) + 4 * Power(y, 2)) * dr_dy(x, y, z)
                              + (3 * Power(a, 3) + 7 * M * x * y) * dr_dx(x, y, z)))
            + 2 * Power(a, 7) * Power(z, 3) * Power(r(x, y, z), 2)
                  * ((2 * a * x + 3 * M * y) * z * dr_dz(x, y, z)
                     + a * (-(a * y) + 3 * Power(z, 2) * dr_dx(x, y, z)))
            - Power(a, 2) * Power(r(x, y, z), 9)
                  * (4 * a * (a * x - M * y) * z
                     + (Power(a, 3) * y + 2 * (2 * M * x + a * y) * Power(z, 2)) * dr_dz(x, y, z)
                     + 6 * M * z * (-(x * y * dr_dy(x, y, z)) + (y - z) * (y + z) * dr_dx(x, y, z)))
            + 2 * Power(r(x, y, z), 11)
                  * ((-2 * Power(a, 3) * y + M * x * (Power(x, 2) + Power(y, 2) - 2 * Power(z, 2)))
                         * dr_dz(x, y, z)
                     + z
                           * (-(Power(a, 2) * x) + 2 * a * M * y - 3 * M * x * y * dr_dy(x, y, z)
                              + M * (-2 * Power(x, 2) + Power(y, 2) + Power(z, 2))
                                    * dr_dx(x, y, z)))
            + Power(a, 4) * Power(z, 2) * Power(r(x, y, z), 5)
                  * ((2 * Power(a, 3) * y + (12 * M * x + a * y) * Power(z, 2)) * dr_dz(x, y, z)
                     + 2 * z
                           * (-2 * a * (a * x + M * y) + 3 * M * x * y * dr_dy(x, y, z)
                              + M * (Power(a, 2) + 4 * Power(x, 2) + Power(y, 2) + 3 * Power(z, 2))
                                    * dr_dx(x, y, z)))
            + 2 * Power(a, 3) * z * Power(r(x, y, z), 6)
                  * (-(a * (Power(a, 3) * y + (6 * M * x + a * y) * Power(z, 2)))
                     + z
                           * ((2 * Power(a, 3) * x - Power(a, 2) * M * y + a * x * Power(z, 2)
                               + M * y * (Power(x, 2) + Power(y, 2) + Power(z, 2)))
                                  * dr_dz(x, y, z)
                              - M * Power(x, 2) * z * dr_dy(x, y, z)
                              + z * (M * x * y + a * Power(z, 2)) * dr_dx(x, y, z)))))
        / (Power(Power(a, 2) + Power(r(x, y, z), 2), 2)
           * Power(Power(a, 2) * Power(z, 2) + Power(r(x, y, z), 4), 2)
           * (Power(a, 4) * Power(z, 2) + 2 * Power(a, 2) * M * Power(z, 2) * r(x, y, z)
              + Power(a, 2) * Power(z, 2) * Power(r(x, y, z), 2)
              + 2 * M * (Power(x, 2) + Power(y, 2) + Power(z, 2)) * Power(r(x, y, z), 3)
              + Power(a, 2) * Power(r(x, y, z), 4) + Power(r(x, y, z), 6))
           * Sqrt(
               1
               - (2 * M * Power(r(x, y, z), 3) * (Power(a, 2) + Power(r(x, y, z), 2)))
                     / (Power(a, 4) * Power(z, 2) + 2 * Power(a, 2) * M * Power(z, 2) * r(x, y, z)
                        + Power(a, 2) * Power(z, 2) * Power(r(x, y, z), 2)
                        + 2 * M * (Power(x, 2) + Power(y, 2) + Power(z, 2)) * Power(r(x, y, z), 3)
                        + Power(a, 2) * Power(r(x, y, z), 4) + Power(r(x, y, z), 6))));
  K[1][1]
      = (2 * M * Power(r(x, y, z), 2)
         * (Power(r(x, y, z), 16) - 3 * Power(a, 11) * x * Power(z, 4) * dr_dy(x, y, z)
            + 2 * Power(a, 9) * (-(M * x) + 2 * a * y) * Power(z, 4) * r(x, y, z) * dr_dy(x, y, z)
            - 4 * Power(a, 2) * y * Power(r(x, y, z), 13) * dr_dy(x, y, z)
            - 2 * y * Power(r(x, y, z), 15) * dr_dy(x, y, z)
            + 3 * a * Power(r(x, y, z), 14) * (a + x * dr_dy(x, y, z))
            + Power(a, 8) * Power(z, 3) * Power(r(x, y, z), 2)
                  * (3 * M * Power(x, 2) * dr_dz(x, y, z)
                     + z * (Power(a, 2) + (-7 * a * x + 2 * M * y) * dr_dy(x, y, z)))
            + Power(r(x, y, z), 12)
                  * (3 * Power(a, 4) - 4 * a * M * x * y + 2 * Power(a, 2) * Power(z, 2)
                     - 3 * M * Power(y, 2) * z * dr_dz(x, y, z)
                     + (7 * Power(a, 3) * x
                        + M * y * (2 * Power(x, 2) - Power(y, 2) + 2 * Power(z, 2)))
                           * dr_dy(x, y, z)
                     - 3 * M * x * Power(y, 2) * dr_dx(x, y, z))
            + Power(a, 6) * Power(z, 2) * Power(r(x, y, z), 4)
                  * (a * (8 * M * x * y + 3 * a * Power(z, 2))
                     + M * (2 * Power(x, 2) + 5 * Power(y, 2)) * z * dr_dz(x, y, z)
                     + (-2 * Power(a, 3) * x + 11 * M * Power(x, 2) * y - 5 * a * x * Power(z, 2)
                        + 6 * M * y * Power(z, 2))
                           * dr_dy(x, y, z)
                     + M * x * (3 * Power(x, 2) - 8 * Power(y, 2)) * dr_dx(x, y, z))
            + a * Power(r(x, y, z), 11)
                  * (4 * a * M * (x - y) * (x + y) + 8 * M * x * y * z * dr_dz(x, y, z)
                     - (2 * Power(a, 3) * y
                        + M * x * (2 * Power(x, 2) - 9 * Power(y, 2) + 2 * Power(z, 2)))
                           * dr_dy(x, y, z)
                     + M * y * (8 * Power(x, 2) - 3 * Power(y, 2)) * dr_dx(x, y, z))
            + Power(a, 2) * Power(r(x, y, z), 10)
                  * (Power(a, 4) + 6 * Power(a, 2) * Power(z, 2)
                     - M * (5 * Power(x, 2) + 2 * Power(y, 2)) * z * dr_dz(x, y, z)
                     + (5 * Power(a, 3) * x - 11 * M * Power(x, 2) * y + 3 * M * Power(y, 3)
                        + 2 * (a * x + 3 * M * y) * Power(z, 2))
                           * dr_dy(x, y, z)
                     + M * x * (-5 * Power(x, 2) + 9 * Power(y, 2)) * dr_dx(x, y, z))
            + Power(a, 3) * Power(r(x, y, z), 7)
                  * (2 * a * M * (Power(x, 2) - 4 * Power(y, 2)) * Power(z, 2)
                     + (Power(a, 2) * M * Power(x, 3)
                        + (-2 * M * x * (3 * Power(a, 2) + Power(x, 2)) + 8 * Power(a, 3) * y
                           - 3 * M * x * Power(y, 2))
                              * Power(z, 2)
                        + 2 * (-(M * x) + a * y) * Power(z, 4))
                           * dr_dy(x, y, z)
                     + M * y * (-(a * x) + y * z) * (a * x + y * z) * dr_dx(x, y, z))
            + Power(a, 2) * Power(r(x, y, z), 8)
                  * (Power(a, 2) * (4 * a * M * x * y + 6 * Power(a, 2) * Power(z, 2) + Power(z, 4))
                     + M * z
                           * (Power(a, 2) * (-6 * Power(x, 2) + Power(y, 2))
                              + Power(y, 2) * Power(z, 2))
                           * dr_dz(x, y, z)
                     + (Power(a, 2) * x * (Power(a, 3) - M * x * y)
                        + (2 * Power(a, 3) * x + 2 * M * (3 * Power(a, 2) + Power(x, 2)) * y
                           + 3 * M * Power(y, 3))
                              * Power(z, 2)
                        + 2 * M * y * Power(z, 4))
                           * dr_dy(x, y, z)
                     + M * x * (-(Power(a, 2) * Power(x, 2)) + Power(y, 2) * Power(z, 2))
                           * dr_dx(x, y, z))
            + Power(a, 7) * Power(z, 2) * Power(r(x, y, z), 3)
                  * (-8 * M * x * y * z * dr_dz(x, y, z)
                     + (10 * a * y * Power(z, 2) - 3 * M * (Power(x, 3) + 2 * x * Power(z, 2)))
                           * dr_dy(x, y, z)
                     + M * Power(x, 2) * (-2 * a + 3 * y * dr_dx(x, y, z)))
            + Power(a, 4) * z * Power(r(x, y, z), 6)
                  * (-(M
                       * (Power(a, 2) * Power(x, 2) + (Power(x, 2) - 6 * Power(y, 2)) * Power(z, 2))
                       * dr_dz(x, y, z))
                     + z
                           * (a * (2 * Power(a, 3) + 8 * M * x * y + 3 * a * Power(z, 2))
                              + (-2 * Power(a, 3) * x + 2 * Power(a, 2) * M * y
                                 - a * x * Power(z, 2)
                                 + M * y * (Power(x, 2) + 7 * Power(y, 2) + 6 * Power(z, 2)))
                                    * dr_dy(x, y, z)
                              - M * x * (Power(x, 2) - 5 * Power(y, 2)) * dr_dx(x, y, z)))
            + Power(a, 2) * Power(r(x, y, z), 9)
                  * (8 * a * M * x * y * z * dr_dz(x, y, z)
                     + a
                           * (4 * a * y * Power(z, 2)
                              + 3 * M * x * (Power(x, 2) - Power(y, 2) - 2 * Power(z, 2)))
                           * dr_dy(x, y, z)
                     + M
                           * (4 * Power(a, 2) * (x - y) * (x + y) - 2 * Power(y, 2) * Power(z, 2)
                              + a * y * (-5 * Power(x, 2) + Power(y, 2)) * dr_dx(x, y, z)))
            + Power(a, 5) * Power(z, 2) * Power(r(x, y, z), 5)
                  * (-8 * M * x * y * z * dr_dz(x, y, z)
                     + (-2 * Power(a, 2) * M * x + 4 * Power(a, 3) * y + 8 * a * y * Power(z, 2)
                        - M * x * (Power(x, 2) + 15 * Power(y, 2) + 6 * Power(z, 2)))
                           * dr_dy(x, y, z)
                     + M * y
                           * (-6 * a * y + (-9 * Power(x, 2) + 5 * Power(y, 2)) * dr_dx(x, y, z)))))
        / (Power(Power(a, 2) + Power(r(x, y, z), 2), 3)
           * Power(Power(a, 2) * Power(z, 2) + Power(r(x, y, z), 4), 2)
           * (Power(a, 4) * Power(z, 2) + 2 * Power(a, 2) * M * Power(z, 2) * r(x, y, z)
              + Power(a, 2) * Power(z, 2) * Power(r(x, y, z), 2)
              + 2 * M * (Power(x, 2) + Power(y, 2) + Power(z, 2)) * Power(r(x, y, z), 3)
              + Power(a, 2) * Power(r(x, y, z), 4) + Power(r(x, y, z), 6))
           * Sqrt(
               1
               - (2 * M * Power(r(x, y, z), 3) * (Power(a, 2) + Power(r(x, y, z), 2)))
                     / (Power(a, 4) * Power(z, 2) + 2 * Power(a, 2) * M * Power(z, 2) * r(x, y, z)
                        + Power(a, 2) * Power(z, 2) * Power(r(x, y, z), 2)
                        + 2 * M * (Power(x, 2) + Power(y, 2) + Power(z, 2)) * Power(r(x, y, z), 3)
                        + Power(a, 2) * Power(r(x, y, z), 4) + Power(r(x, y, z), 6))));
  K[1][2]
      = (M * r(x, y, z)
         * (3 * a * x * Power(r(x, y, z), 13) * dr_dz(x, y, z)
            + 2 * Power(a, 10) * Power(z, 5) * dr_dy(x, y, z)
            - 2 * Power(r(x, y, z), 14) * (y * dr_dz(x, y, z) + z * dr_dy(x, y, z))
            - 2 * Power(a, 2) * Power(r(x, y, z), 12)
                  * (y * dr_dz(x, y, z) + 3 * z * dr_dy(x, y, z))
            + Power(a, 8) * Power(z, 4) * r(x, y, z)
                  * (-3 * a * x * dr_dz(x, y, z) + 2 * M * z * dr_dy(x, y, z))
            + 2 * Power(a, 7) * Power(z, 3) * Power(r(x, y, z), 2)
                  * ((-3 * M * x + 2 * a * y) * z * dr_dz(x, y, z)
                     + a * (a * x + 3 * Power(z, 2) * dr_dy(x, y, z)))
            + 2 * Power(a, 6) * Power(z, 3) * Power(r(x, y, z), 3)
                  * (a * (2 * M * x - a * y) + (-2 * a * x * z + 4 * M * y * z) * dr_dz(x, y, z)
                     + M * (2 * Power(x, 2) + 3 * Power(z, 2)) * dr_dy(x, y, z)
                     - 2 * M * x * y * dr_dx(x, y, z))
            - 2 * Power(a, 2) * z * Power(r(x, y, z), 8)
                  * (-2 * Power(a, 3) * x + 2 * Power(a, 2) * M * y + 2 * M * y * Power(z, 2)
                     - 2 * a * (2 * M * x + a * y) * z * dr_dz(x, y, z)
                     + a * (Power(a, 3) - 3 * M * x * y) * dr_dy(x, y, z)
                     + a * M * (-2 * Power(x, 2) + Power(y, 2)) * dr_dx(x, y, z))
            + 2 * Power(a, 5) * Power(z, 3) * Power(r(x, y, z), 4)
                  * (2 * a * (a * x - 2 * M * y) + (-4 * M * x + 3 * a * y) * z * dr_dz(x, y, z)
                     + (-5 * M * x * y + 3 * a * Power(z, 2)) * dr_dy(x, y, z)
                     + M * (-2 * Power(x, 2) + 3 * Power(y, 2)) * dr_dx(x, y, z))
            + 2 * Power(a, 2) * z * Power(r(x, y, z), 7)
                  * (-(Power(a, 2) * y * (Power(a, 2) + Power(z, 2)))
                     + M * y * z * (Power(x, 2) + Power(y, 2) + 2 * Power(z, 2)) * dr_dz(x, y, z)
                     + M
                           * (-2 * Power(a, 2) * Power(x, 2)
                              + (3 * Power(a, 2) + Power(x, 2) + 2 * Power(y, 2)) * Power(z, 2)
                              + Power(z, 4))
                           * dr_dy(x, y, z)
                     + M * x * y * (2 * Power(a, 2) + Power(z, 2)) * dr_dx(x, y, z))
            + Power(a, 2) * Power(r(x, y, z), 9)
                  * (-4 * a * (M * x + a * y) * z
                     + (Power(a, 3) * x + 2 * (a * x - 2 * M * y) * Power(z, 2)) * dr_dz(x, y, z)
                     + 6 * M * z
                           * ((-Power(x, 2) + Power(z, 2)) * dr_dy(x, y, z)
                              + x * y * dr_dx(x, y, z)))
            + 2 * Power(r(x, y, z), 11)
                  * ((2 * Power(a, 3) * x + M * y * (Power(x, 2) + Power(y, 2) - 2 * Power(z, 2)))
                         * dr_dz(x, y, z)
                     + z
                           * (-(a * (2 * M * x + a * y))
                              + M * (Power(x, 2) - 2 * Power(y, 2) + Power(z, 2)) * dr_dy(x, y, z)
                              - 3 * M * x * y * dr_dx(x, y, z)))
            + Power(a, 4) * Power(z, 2) * Power(r(x, y, z), 5)
                  * (-((2 * Power(a, 3) * x + (a * x - 12 * M * y) * Power(z, 2)) * dr_dz(x, y, z))
                     + 2 * z
                           * (2 * a * (M * x - a * y)
                              + M * (Power(a, 2) + Power(x, 2) + 4 * Power(y, 2) + 3 * Power(z, 2))
                                    * dr_dy(x, y, z)
                              + 3 * M * x * y * dr_dx(x, y, z)))
            - 2 * a * Power(r(x, y, z), 10)
                  * (M * x * (Power(x, 2) + Power(y, 2) - 3 * Power(z, 2)) * dr_dz(x, y, z)
                     + z
                           * (a * (-(a * x) + 2 * M * y)
                              + (3 * Power(a, 3) - 7 * M * x * y) * dr_dy(x, y, z)
                              + M * (-4 * Power(x, 2) + 3 * Power(y, 2)) * dr_dx(x, y, z)))
            + 2 * Power(a, 3) * z * Power(r(x, y, z), 6)
                  * (Power(a, 4) * x + a * (a * x - 6 * M * y) * Power(z, 2)
                     + z
                           * ((Power(a, 2) * M * x + 2 * Power(a, 3) * y + a * y * Power(z, 2)
                               - M * x * (Power(x, 2) + Power(y, 2) + Power(z, 2)))
                                  * dr_dz(x, y, z)
                              + z * (-(M * x * y) + a * Power(z, 2)) * dr_dy(x, y, z)
                              + M * Power(y, 2) * z * dr_dx(x, y, z)))))
        / (Power(Power(a, 2) + Power(r(x, y, z), 2), 2)
           * Power(Power(a, 2) * Power(z, 2) + Power(r(x, y, z), 4), 2)
           * (Power(a, 4) * Power(z, 2) + 2 * Power(a, 2) * M * Power(z, 2) * r(x, y, z)
              + Power(a, 2) * Power(z, 2) * Power(r(x, y, z), 2)
              + 2 * M * (Power(x, 2) + Power(y, 2) + Power(z, 2)) * Power(r(x, y, z), 3)
              + Power(a, 2) * Power(r(x, y, z), 4) + Power(r(x, y, z), 6))
           * Sqrt(
               1
               - (2 * M * Power(r(x, y, z), 3) * (Power(a, 2) + Power(r(x, y, z), 2)))
                     / (Power(a, 4) * Power(z, 2) + 2 * Power(a, 2) * M * Power(z, 2) * r(x, y, z)
                        + Power(a, 2) * Power(z, 2) * Power(r(x, y, z), 2)
                        + 2 * M * (Power(x, 2) + Power(y, 2) + Power(z, 2)) * Power(r(x, y, z), 3)
                        + Power(a, 2) * Power(r(x, y, z), 4) + Power(r(x, y, z), 6))));
  K[2][2]
      = (2 * M * r(x, y, z)
         * (2 * Power(a, 2) * Power(r(x, y, z), 11) + Power(r(x, y, z), 13)
            + 2 * Power(a, 8) * Power(z, 5) * dr_dz(x, y, z)
            - 4 * Power(a, 2) * z * Power(r(x, y, z), 10) * dr_dz(x, y, z)
            - 2 * z * Power(r(x, y, z), 12) * dr_dz(x, y, z)
            - Power(a, 6) * Power(z, 4) * r(x, y, z) * (Power(a, 2) - 3 * M * z * dr_dz(x, y, z))
            - Power(a, 2) * M * Power(z, 2) * Power(r(x, y, z), 7)
                  * (2 * z * dr_dz(x, y, z) + 3 * y * dr_dy(x, y, z) + 3 * x * dr_dx(x, y, z))
            + Power(a, 4) * Power(z, 4) * Power(r(x, y, z), 3)
                  * (-2 * Power(a, 2) + 6 * M * z * dr_dz(x, y, z) + M * y * dr_dy(x, y, z)
                     + M * x * dr_dx(x, y, z))
            + Power(a, 2) * M * Power(z, 2) * Power(r(x, y, z), 6)
                  * (-2 * Power(z, 2) + 3 * a * x * dr_dy(x, y, z) - 3 * a * y * dr_dx(x, y, z))
            + Power(a, 2) * Power(z, 3) * Power(r(x, y, z), 5)
                  * (M * (-Power(a, 2) + 2 * (Power(x, 2) + Power(y, 2)) + 3 * Power(z, 2))
                         * dr_dz(x, y, z)
                     + z * (-Power(a, 2) + M * y * dr_dy(x, y, z) + M * x * dr_dx(x, y, z)))
            + a * z * Power(r(x, y, z), 8)
                  * (-2 * Power(a, 3) * dr_dz(x, y, z)
                     + 3 * M * z * (x * dr_dy(x, y, z) - y * dr_dx(x, y, z)))
            + Power(a, 3) * Power(z, 4) * Power(r(x, y, z), 4)
                  * (2 * a * z * dr_dz(x, y, z)
                     + M * (-4 * a - x * dr_dy(x, y, z) + y * dr_dx(x, y, z)))
            + Power(a, 5) * Power(z, 4) * Power(r(x, y, z), 2)
                  * (4 * a * z * dr_dz(x, y, z)
                     + M * (-2 * a - x * dr_dy(x, y, z) + y * dr_dx(x, y, z)))
            + Power(r(x, y, z), 9)
                  * (Power(a, 4)
                     - M * z
                           * ((-2 * (Power(x, 2) + Power(y, 2)) + Power(z, 2)) * dr_dz(x, y, z)
                              + 3 * z * (y * dr_dy(x, y, z) + x * dr_dx(x, y, z))))))
        / ((Power(a, 2) + Power(r(x, y, z), 2))
           * Power(Power(a, 2) * Power(z, 2) + Power(r(x, y, z), 4), 2)
           * (Power(a, 4) * Power(z, 2) + 2 * Power(a, 2) * M * Power(z, 2) * r(x, y, z)
              + Power(a, 2) * Power(z, 2) * Power(r(x, y, z), 2)
              + 2 * M * (Power(x, 2) + Power(y, 2) + Power(z, 2)) * Power(r(x, y, z), 3)
              + Power(a, 2) * Power(r(x, y, z), 4) + Power(r(x, y, z), 6))
           * Sqrt(
               1
               - (2 * M * Power(r(x, y, z), 3) * (Power(a, 2) + Power(r(x, y, z), 2)))
                     / (Power(a, 4) * Power(z, 2) + 2 * Power(a, 2) * M * Power(z, 2) * r(x, y, z)
                        + Power(a, 2) * Power(z, 2) * Power(r(x, y, z), 2)
                        + 2 * M * (Power(x, 2) + Power(y, 2) + Power(z, 2)) * Power(r(x, y, z), 3)
                        + Power(a, 2) * Power(r(x, y, z), 4) + Power(r(x, y, z), 6))));
  K[1][0] = K[0][1];
  K[2][0] = K[0][2];
  K[2][1] = K[1][2];

  return K;
}