
#ifndef GRLENSING_SKS_METRIC_OPTIONS_HPP
#define GRLENSING_SKS_METRIC_OPTIONS_HPP

#define GRLENSING_SKS_METRIC_VERSION_MAJOR 1 // NOLINT
#define GRLENSING_SKS_METRIC_VERSION_MINOR 0 // NOLINT
#define GRLENSING_SKS_METRIC_VERSION_PATCH 0 // NOLINT

#define GRLENSING_SKS_METRIC_SYSTEM_Linux
#define GRLENSING_SKS_METRIC_COMPILER_GNU

#endif // GRLENSING_SKS_METRIC_OPTIONS_HPP
