#ifndef GRLENSING_ASCII_WRITER_OPTIONS_HPP
#define GRLENSING_ASCII_WRITER_OPTIONS_HPP

#define GRLENSING_ASCII_WRITER_VERSION_MAJOR 1 // NOLINT
#define GRLENSING_ASCII_WRITER_VERSION_MINOR 0 // NOLINT
#define GRLENSING_ASCII_WRITER_VERSION_PATCH 0 // NOLINT

#define GRLENSING_ASCII_WRITER_SYSTEM_Linux
#define GRLENSING_ASCII_WRITER_COMPILER_GNU

#endif // GRLENSING_ASCII_WRITER_OPTIONS_HPP
