---
#############################################################
# Particle breakup process settings                         #
#############################################################

background_metric: "Kerr-Schild Kerr"
background_radius: 10000000.0

KerrSchild_Kerr_Settings:
  M: 1.0
  a: 0.99

energy_threshold: 1.0

output_format: ".ascii"

# Zero for photons, anything else for massive.
particle_type: 1

breakup_point:
  X1: 1.59
  X2: 0.0
  X3: 0.0

trajectory_1:
  final_time: -100000000.0
  output_times: 100
  
  initial_V1: 0.7789735389507061
  initial_V2: 0.4682741900689633
  initial_V3: 0.0
  
  initial_EN: 1.0

trajectory_2:
  final_time: 100000000.0
  output_times: 100

  initial_V1: +0.5108386445934677
  initial_V2: -0.3516948620452038
  initial_V3: 0.0

  initial_EN: 1.2e-2

trajectory_3:
  final_time: 100000000.0
  output_times: 100
