---
#############################################################
# Particle breakup process settings                         #
#############################################################

background_metric: "Superimposed Kerr binary in Kerr-Schild coordinates"
background_radius: 10000.0

SKS_Settings:
  M1: 0.5
  M2: 0.5
  a1: 0.475
  a2: 0.475
  b: 10.0

energy_threshold: 1.0

output_format: ".ascii"

# Zero for photons, anything else for massive.
particle_type: 1

breakup_point:
  X1: -6.2772
  X2: 0.0
  X3: 0.0

trajectory_1:
  final_time: -10000.0
  output_times: 1000
  
  initial_V1: -0.632
  initial_V2: -0.720
  initial_V3: 0.0
  
  initial_EN: 5.0

trajectory_2:
  final_time: 10000.0
  output_times: 1000

  initial_V1: 0.1
  initial_V2: -0.7
  initial_V3: 0.0
  
  initial_EN: 0.01

trajectory_3:
  final_time: 10000.0
  output_times: 1000