---
#############################################################
# Trajectory settings                                       #
#############################################################

initial_time: 0.0
final_time: 100.0

# How many times to output between initial and final time
output_times: 100

initial_V1: 0.6229495642339938
initial_V2: -0.3287208208237976
initial_V3: 0.0

initial_X1: 6.3
initial_X2: 0.0
initial_X3: 0.0

initial_EN: 1.0

output_file: "sks_trajectory.ascii"
metadata_file: "sks_trajectory_metadata.ascii"

background_metric: "Superimposed Kerr binary in Kerr-Schild coordinates"

background_radius: 10.0
energy_threshold: 1.0

# Zero for photons, anything else for massive.
particle_type: 1

SKS_Settings:
  M1: 0.5
  M2: 0.5
  a1: 0.49
  a2: 0.49
  b: 10.0