#ifndef GRLENSING_OPTIONS_HPP
#define GRLENSING_OPTIONS_HPP

#define GRLENSING_VERSION_MAJOR 1 // NOLINT
#define GRLENSING_VERSION_MINOR 0 // NOLINT
#define GRLENSING_VERSION_PATCH 0 // NOLINT

#define GRLENSING_SYSTEM_Linux
#define GRLENSING_COMPILER_GNU

#define GRLENSING_USE_LOG_COLOR

#endif // GRLENSING_OPTIONS_HPP
